<?php namespace App\Http\Controllers;

use DB;
use Excel;
use Log;
use Event;
use App\Events\ParticipeRegistered;
use Illuminate\Http\Request;

class WelcomeController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	
		$this->middleware('guest');
	
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index() {
	
		return view('welcome');
	
	}

	/**
	 * Create record using details submitted from Inscreva-se form
	 *
	 * @return Response
	 */
	public function InscrevaSe(Request $request) {

		DB::insert("INSERT INTO inscreva_se (nome_do_participante, funcao, telemovel, email, nome_da_oficina, morada, codigo_postal, localidade, telefone) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [
				$request->input('inscreva_nome_do_participante'),
				$request->input('inscreva_funcao'),
				$request->input('inscreva_telemovel'),
				$request->input('inscreva_email'),
				$request->input('inscreva_nome_da_oficina'),
				$request->input('inscreva_morada'),
				$request->input('inscreva_codigo_postal'),
				$request->input('inscreva_localidade'),
				$request->input('inscreva_telefone')
		]);

		return response()->json(['status' => 200]);
	
	}

	/**
	 * Create record using details submitted from Participe form
	 *
	 * @return Response
	 */
	public function Participe(Request $request) {

		DB::insert("INSERT INTO participe (nome, telemovel, email, nome_da_oficina, alugueres) VALUES (?, ?, ?, ?, ?)", [
				$request->input('participe_nome'),
				$request->input('participe_telemovel'),
				$request->input('participe_email'),
				$request->input('participe_nome_da_oficina'),
				$request->input('participe_alugueres')
		]);

		$data = (object) array(
			'inscreva_se' => DB::select("SELECT * FROM inscreva_se WHERE id >= :id", ["id" => 1]),
			'participe' => (object) array(
				'name' => $request->input('participe_nome'),
				'email' => $request->input('participe_email')
			)
		);

		$response = Excel::create('Inscreva_se_'.date('YmdHis'), function($excel) use ($data) {
			
			// assigning document properties
			$excel->setTitle('Porto Inc')
				  ->setCreator('Sebastian Njose')
				  ->setCompany('Porto Inc')
				  ->setDescription('Excel document generated by Porto Inc');
			
			// create worksheet
			$excel->sheet('Entries', function($sheet) use ($data) {
				
				// define columns
				$sheet->appendRow([
					'Nome do participante',
					'Funcao',
					'Telemovel',
					'Email',
					'Nome da Oficina',
					'Morada',
					'Codigo Postal',
					'Localidade',
					'Telefone'
				]);
				
				foreach ($data->inscreva_se as $row) {
					$sheet->appendRow([
						$row->nome_do_participante,
						$row->funcao,
						$row->telemovel,
						$row->email,
						$row->nome_da_oficina,
						$row->morada,
						$row->codigo_postal,
						$row->localidade,
						$row->telefone
					]);
				}

			});

		})->store('xls', false, true);

		if (is_array($response)):

			$data->participe->file = $response['file'];

			Event::fire(new ParticipeRegistered($data->participe));
		
		endif;

		return response()->json(['status' => 200]);
	
	}

}
